### ISSUE TITLE
bad option: --transpileOnly

### ISSUE THREAD

**Issue by goodforever** [cortezaproject/corteza-server-corredor#12]
yarn serve:dev
yarn run v1.9.4
$ ts-node-dev --debounce 200 --transpileOnly --respawn --ignore-watch node_modules --ignore-watch usr --ignore-watch dist ./src/server.ts
[INFO] 10:51:14 ts-node-dev ver. 1.1.1 (using ts-node ver. 9.1.1, typescript ver. 3.9.7)
/usr/local/bin/node: bad option: --transpileOnly

**Comment by Fajfa** [comment]
Thank you for opening this issue.
For now the fix is to change the --transpileOnly to --transpile-only in package.json.
This has been fixed here:  https://github.com/cortezaproject/corteza-server-corredor/commit/e029093eebe610954d05bfb6c7afa197037d7968
