### ISSUE TITLE
Getting error while runing script from workflow

### ISSUE THREAD

**Issue by jitendraflowz03** [cortezaproject/corteza-server-corredor#40]
Hello team,

When i'm running script from workflow it;s getting error `step 4 crashed: runtime error: invalid memory address or nil pointer dereference`

![image](https://user-images.githubusercontent.com/89089409/156370679-db249e1b-ef78-4bd9-8422-bd0157d7a424.png)

Version : 2021.9

**Comment by skamensky** [comment]
@jitendraflowz03 ,

I had a similar error and reported it [here](https://forum.cortezaproject.org/t/simple-corredor-script-results-in-runtime-error-invalid-memory-address-or-nil-pointer-dereference) but never got an answer.

How did you fix this?
